#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["FoodHub.UserManagement/FoodHub.UserManagement.csproj", "FoodHub.UserManagement/"]
RUN dotnet restore "FoodHub.UserManagement/FoodHub.UserManagement.csproj"
COPY . .
WORKDIR "/src/FoodHub.UserManagement"
RUN dotnet build "FoodHub.UserManagement.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FoodHub.UserManagement.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FoodHub.UserManagement.dll"]